/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 macbook.glb --transform
Files: macbook.glb [5.48MB] > /Users/aleksandr/Downloads/macbook-transformed.glb [457.95KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
    const { nodes, materials } = useGLTF('/macbook-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.abgVijaHVNRUvcc.geometry} material={materials.PaletteMaterial001} scale={0.01} />
            <mesh geometry={nodes.CEvArJuvvmtQsgk.geometry} material={materials.PaletteMaterial002} scale={0.01} />
            <mesh geometry={nodes.zlRXoydEgBQgFUa.geometry} material={materials.zqeFZcIteZtOShc} scale={0.01} />
            <mesh geometry={nodes.ehiyYGFzDbgxhiD.geometry} material={materials.LJSCtLIrHNHZnIH} scale={0.01} />
            <mesh geometry={nodes.yxTDdMZViYkuOKm.geometry} material={materials.PaletteMaterial003} scale={0.01} />
            <mesh geometry={nodes.UxiDBlCRfXiMBzT.geometry} material={materials.zWLcvvnJhbcTEtJ} scale={0.01} />
            <mesh geometry={nodes.NgmQYtxXWDmCavo.geometry} material={materials.SKOFticEGTqECbB} scale={0.01} />
            <mesh geometry={nodes.KCEhahuknsxQOxv.geometry} material={materials.HpEeGHRuOqfcIZU} scale={0.01} />
            <mesh geometry={nodes.eAcvqfZlEdoxHsj.geometry} material={materials.IlNnjEDxsExlBOr} scale={0.01} />
            <mesh geometry={nodes.xlRLalLTesirCGW.geometry} material={materials.hPcehRUjcLAosED} scale={0.01} />
            <mesh geometry={nodes.wXiLpiodZWNDroe.geometry} material={materials.PaletteMaterial004} scale={0.01} />
            <mesh geometry={nodes.QHqPxKdexBoFnAK.geometry} material={materials.PaletteMaterial005} scale={0.01} />
            <mesh geometry={nodes.NWErafhynAfYQEz.geometry} material={materials.pZbDFXVUkfRwjmQ} scale={0.01} />
            <mesh geometry={nodes.QMBrsnrwfcVKELm.geometry} material={materials.VqwNZwmDotIMflD} scale={0.01} />
        </group>
    )
}

useGLTF.preload('/macbook-transformed.glb')
