/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 2021_macbook_pro_14_m1_pro__m1_max.glb --transform
Files: 2021_macbook_pro_14_m1_pro__m1_max.glb [6.19MB] > /Users/aleksandr/Downloads/2021_macbook_pro_14_m1_pro__m1_max-transformed.glb [552.1KB] (91%)
Author: akshatmittal (https://sketchfab.com/akshatmittal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2021-macbook-pro-14-m1-pro-m1-max-f6b0b940fb6a4286b18a674ef32af2d3
Title: 2021 Macbook Pro 14" (M1 Pro / M1 Max)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/2021_macbook_pro_14_m1_pro__m1_max-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.abgVijaHVNRUvcc.geometry} material={materials.PaletteMaterial001} scale={0.01} />
      <mesh geometry={nodes.CEvArJuvvmtQsgk.geometry} material={materials.PaletteMaterial002} scale={0.01} />
      <mesh geometry={nodes.zlRXoydEgBQgFUa.geometry} material={materials.zqeFZcIteZtOShc} scale={0.01} />
      <mesh geometry={nodes.ehiyYGFzDbgxhiD.geometry} material={materials.LJSCtLIrHNHZnIH} scale={0.01} />
      <mesh geometry={nodes.yxTDdMZViYkuOKm.geometry} material={materials.PaletteMaterial003} scale={0.01} />
      <mesh geometry={nodes.UxiDBlCRfXiMBzT.geometry} material={materials.zWLcvvnJhbcTEtJ} scale={0.01} />
      <mesh geometry={nodes.NgmQYtxXWDmCavo.geometry} material={materials.SKOFticEGTqECbB} scale={0.01} />
      <mesh geometry={nodes.KCEhahuknsxQOxv.geometry} material={materials.HpEeGHRuOqfcIZU} scale={0.01} />
      <mesh geometry={nodes.eAcvqfZlEdoxHsj.geometry} material={materials.IlNnjEDxsExlBOr} scale={0.01} />
      <mesh geometry={nodes.xlRLalLTesirCGW.geometry} material={materials.hPcehRUjcLAosED} scale={0.01} />
      <mesh geometry={nodes.wXiLpiodZWNDroe.geometry} material={materials.PaletteMaterial004} scale={0.01} />
      <mesh geometry={nodes.QHqPxKdexBoFnAK.geometry} material={materials.PaletteMaterial005} scale={0.01} />
      <mesh geometry={nodes.NWErafhynAfYQEz.geometry} material={materials.pZbDFXVUkfRwjmQ} scale={0.01} />
      <mesh geometry={nodes.VqfccLWHjnpnmIO.geometry} material={materials.BMKLbAPYqPmfArt} scale={0.01} />
      <mesh geometry={nodes.QMBrsnrwfcVKELm.geometry} material={materials.VqwNZwmDotIMflD} scale={0.01} />
    </group>
  )
}

