/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 canon7.glb --transform
Files: canon7.glb [72.14MB] > /Users/aleksandr/Documents/WebStormProj/personal-page/public/canon7-transformed.glb [839.06KB] (99%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Canon7(props) {
  const { nodes, materials } = useGLTF('/canon7-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} position={[0.161, -0.75, -0.213]} />
    </group>
  )
}

