/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kiev60.glb --transform --simplify
Files: kiev60.glb [100.99MB] > /Users/aleksandr/Downloads/kiev60-transformed.glb [5.87MB] (94%)
Author: GoMeasure3D (https://sketchfab.com/gomeasure3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kiev-60-film-camera-artec-spider-3d-scan-919baf919de3479eb345090e59fbb832
Title: Kiev 60 Film Camera - Artec Spider 3D Scan
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Kiev60(props) {
  const { nodes, materials } = useGLTF('/kiev60-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} position={[-19.178, -6.398, 4.222]} rotation={[0.597, -0.897, 2.414]} />
    </group>
  )
}

