/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kiev-4-8k.glb --transform --simplify
Files: kiev-4-8k.glb [64.36MB] > /Users/aleksandr/Documents/WebStormProj/personal-page/public/kiev-4-8k-transformed.glb [2.86MB] (96%)
Author: GoMeasure3D (https://sketchfab.com/gomeasure3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kiev-35mm-slr-camera-artec-spider-3d-scan-fd35db24d4c3403c8abd48330e6a894f
Title: Kiev 35mm SLR camera - Artec Spider 3D Scan
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Kiev4(props) {
  const { nodes, materials } = useGLTF('/kiev-4-8k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material_0} scale={0.05} position={[-1.229, 1.446, 8.23]} rotation={[-2.207, -0.061, 0.048]} />
    </group>
  )
}

